/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.measuringsystem.client.presentation;

import co.unicauca.measuringsystem.client.access.Factory;
import co.unicauca.measuringsystem.client.access.IMeasuringSystem;
import co.unicauca.measuringsystem.client.domain.services.MeasuringSystem;
import co.unicauca.measuringsystem.server.domain.Lector;
import co.unicauca.measuringsystem.server.domain.Shooter;
import co.unicauca.measuringsystem.client.domain.*;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Andre
 */
public class GUIIMesuringItem extends javax.swing.JInternalFrame {

	ArrayList<Lector> lectores;
    /**
     * Creates new form GUIItemMedicion
     */
    public GUIIMesuringItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        
        jPanelCentral.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        
        JLabel lblNewLabel = new JLabel("Inserte el evento que quiere que sea detectado:");
        
        txtEventoDelLector = new JTextField();
        txtEventoDelLector.setColumns(10);
        
        JButton btnCrearLector = new JButton("Agregar");
        btnCrearLector.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		try {
        		lectores.add(0, new Lector(txtEventoDelLector.getText()));
        		Shooter disparador = new Shooter(lectores.get(0));
        		lectores.get(0).addSensor(disparador);
        	
        		}catch(Exception e1) {
        			
        		}
        	}
        });
        
        textDato = new JTextField();
        textDato.setColumns(10);
        
        JLabel lblNewLabel_1 = new JLabel("Ingrese una medida (string)");
        
        JButton btnIngresarMedida = new JButton("Ingresar");
        btnIngresarMedida.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		try {
        		if(!lectores.get(0).getSensor(0).medirDatos(textDato.getText())) {
        			JOptionPane.showMessageDialog(null, "Evento detectado!");
        			
        		}
        		JOptionPane.showMessageDialog(null, "Dato leído");
        		}catch(Exception e2) {
        			
        		}
        	}
        });

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentralLayout.setHorizontalGroup(
        	jPanelCentralLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelCentralLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanelCentralLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnCrearLector)
        				.addComponent(txtEventoDelLector, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel))
        			.addGap(220)
        			.addGroup(jPanelCentralLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanelCentralLayout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(textDato)
        					.addComponent(lblNewLabel_1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addComponent(btnIngresarMedida))
        			.addContainerGap(633, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
        	jPanelCentralLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelCentralLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanelCentralLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel)
        				.addComponent(lblNewLabel_1))
        			.addGap(18)
        			.addGroup(jPanelCentralLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtEventoDelLector, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textDato, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanelCentralLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnCrearLector)
        				.addComponent(btnIngresarMedida))
        			.addContainerGap(170, Short.MAX_VALUE))
        );
        jPanelCentral.setLayout(jPanelCentralLayout);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCentral;
    private JTextField txtEventoDelLector;
    private JTextField textDato;
}
